on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Workflow
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          archtecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          pyinstaller -F durepoxi.py
      - name: actions/upload-artifact@v2
        with:
          name: Linux_durepoxi
          path: dist/durepoxi
